/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tfWPIZ3E768
 */
import Image from "next/image";
import Link from "next/link";

export function Header() {
  return (
    <header className="flex items-center  w-full px-4 py-2 md:px-6 bg-gray-200 shadow-lg">
      <Link className="mr-4" href="#">
        <Image src="/logo.png" width={250} height={150} className="rounded-5" />
      </Link>
      <nav className="flex-1 justify-center hidden gap-4 md:flex"></nav>
    </header>
  );
}
